import { PrismaClient, Prisma } from "@prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const gifts: Prisma.GiftCreateInput[] = [
  {
    name: "Wireless Noise-Cancelling Headphones",
    description: "Over-ear Bluetooth headphones with active noise cancellation and 30-hour battery life.",
    price: 199.99,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
    affiliateUrl: "https://www.amazon.com/dp/example-headphones",
    platform: "Amazon",
    occasions: ["Birthday", "Christmas", "Graduation"],
    interests: ["Music", "Tech", "Travel"],
    ageMin: 13,
    ageMax: 99,
  },
  {
    name: "Instant Film Camera",
    description: "Retro-style instant camera that prints credit-card-sized photos on the spot.",
    price: 79.99,
    imageUrl: "https://images.unsplash.com/photo-1495707902641-75cac588d2e9",
    affiliateUrl: "https://www.amazon.com/dp/example-camera",
    platform: "Amazon",
    occasions: ["Birthday", "Graduation"],
    interests: ["Photography", "Art"],
    ageMin: 10,
    ageMax: 60,
  },
  {
    name: "Espresso Machine",
    description: "Compact semi-automatic espresso machine with milk frother for café-quality coffee at home.",
    price: 249.0,
    imageUrl: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6",
    affiliateUrl: "https://www.amazon.com/dp/example-espresso",
    platform: "Amazon",
    occasions: ["Housewarming", "Wedding", "Christmas"],
    interests: ["Coffee", "Cooking"],
    ageMin: 21,
    ageMax: 99,
  },
  {
    name: "Mechanical Gaming Keyboard",
    description: "RGB backlit mechanical keyboard with hot-swappable switches for gaming and typing enthusiasts.",
    price: 129.99,
    imageUrl: "https://images.unsplash.com/photo-1541140532154-b024d705b90a",
    affiliateUrl: "https://www.amazon.com/dp/example-keyboard",
    platform: "Amazon",
    occasions: ["Birthday", "Christmas"],
    interests: ["Gaming", "Tech"],
    ageMin: 12,
    ageMax: 99,
  },
  {
    name: "Cast Iron Dutch Oven",
    description: "Enameled cast iron Dutch oven perfect for braises, stews, and no-knead bread.",
    price: 89.95,
    imageUrl: "https://images.unsplash.com/photo-1584990347449-a2d4c3f2a6e1",
    affiliateUrl: "https://www.amazon.com/dp/example-dutchoven",
    platform: "Amazon",
    occasions: ["Wedding", "Housewarming"],
    interests: ["Cooking"],
    ageMin: 18,
    ageMax: 99,
  },
  {
    name: "Leather Journal Notebook",
    description: "Hand-bound leather journal with refillable, dotted pages for writing or sketching.",
    price: 34.5,
    imageUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363",
    affiliateUrl: "https://www.etsy.com/listing/example-journal",
    platform: "Etsy",
    occasions: ["Graduation", "Birthday", "Anniversary"],
    interests: ["Writing", "Art"],
    ageMin: 14,
    ageMax: 99,
  },
  {
    name: "Smart Fitness Watch",
    description: "Tracks heart rate, sleep, and workouts with a week-long battery and app integration.",
    price: 159.99,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
    affiliateUrl: "https://www.amazon.com/dp/example-fitnesswatch",
    platform: "Amazon",
    occasions: ["Birthday", "Christmas", "New Year"],
    interests: ["Fitness", "Tech", "Health"],
    ageMin: 14,
    ageMax: 80,
  },
  {
    name: "Board Game Collection Set",
    description: "A curated bundle of three award-winning strategy board games for game night.",
    price: 64.99,
    imageUrl: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09",
    affiliateUrl: "https://www.amazon.com/dp/example-boardgames",
    platform: "Amazon",
    occasions: ["Christmas", "Birthday", "Family Gathering"],
    interests: ["Games", "Family"],
    ageMin: 8,
    ageMax: 99,
  },
  {
    name: "Succulent Plant Starter Kit",
    description: "A set of six easy-care succulents with decorative pots, ideal for beginners.",
    price: 42.0,
    imageUrl: "https://images.unsplash.com/photo-1459156212016-c812468e2115",
    affiliateUrl: "https://www.etsy.com/listing/example-succulents",
    platform: "Etsy",
    occasions: ["Housewarming", "Get Well Soon", "Birthday"],
    interests: ["Gardening", "Home Decor"],
    ageMin: 10,
    ageMax: 99,
  },
  {
    name: "Portable Bluetooth Speaker",
    description: "Waterproof, shockproof speaker with 20 hours of playtime, perfect for outdoor adventures.",
    price: 59.99,
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1",
    affiliateUrl: "https://www.amazon.com/dp/example-speaker",
    platform: "Amazon",
    occasions: ["Birthday", "Graduation", "Christmas"],
    interests: ["Music", "Outdoors", "Travel"],
    ageMin: 10,
    ageMax: 99,
  },
  {
    name: "Silk Pillowcase Set",
    description: "100% mulberry silk pillowcases that are gentle on skin and hair.",
    price: 45.0,
    imageUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af",
    affiliateUrl: "https://www.amazon.com/dp/example-silkpillow",
    platform: "Amazon",
    occasions: ["Anniversary", "Mother's Day", "Birthday"],
    interests: ["Beauty", "Home Decor", "Self-care"],
    ageMin: 16,
    ageMax: 99,
  },
  {
    name: "Beginner Watercolor Painting Set",
    description: "A complete kit with paints, brushes, and paper for aspiring watercolor artists.",
    price: 38.75,
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f",
    affiliateUrl: "https://www.etsy.com/listing/example-watercolor",
    platform: "Etsy",
    occasions: ["Birthday", "Christmas"],
    interests: ["Art", "Painting"],
    ageMin: 8,
    ageMax: 99,
  },
  {
    name: "Personalized Star Map Print",
    description: "Custom star map poster showing the night sky from any date and location.",
    price: 49.99,
    imageUrl: "https://images.unsplash.com/photo-1446776653964-20c1d3a81b06",
    affiliateUrl: "https://www.etsy.com/listing/example-starmap",
    platform: "Etsy",
    occasions: ["Anniversary", "Wedding", "Valentine's Day"],
    interests: ["Astronomy", "Home Decor", "Romance"],
    ageMin: 12,
    ageMax: 99,
  },
  {
    name: "Electric Skateboard",
    description: "Commuter-friendly electric skateboard with a 12-mile range and dual motors.",
    price: 349.0,
    imageUrl: "https://images.unsplash.com/photo-1547447134-cd3f5c716030",
    affiliateUrl: "https://www.amazon.com/dp/example-eskateboard",
    platform: "Amazon",
    occasions: ["Birthday", "Graduation", "Christmas"],
    interests: ["Outdoors", "Tech", "Sports"],
    ageMin: 14,
    ageMax: 45,
  },
  {
    name: "Scented Candle Gift Set",
    description: "A trio of soy candles in seasonal scents, hand-poured in reusable glass jars.",
    price: 32.0,
    imageUrl: "https://images.unsplash.com/photo-1602874801007-bd458bb1b8b6",
    affiliateUrl: "https://www.etsy.com/listing/example-candles",
    platform: "Etsy",
    occasions: ["Housewarming", "Christmas", "Get Well Soon"],
    interests: ["Home Decor", "Self-care"],
    ageMin: 12,
    ageMax: 99,
  },
  {
    name: "Kids' Building Block Set",
    description: "A 500-piece creative building block set compatible with major brick brands.",
    price: 54.99,
    imageUrl: "https://images.unsplash.com/photo-1587654780291-39c9404d746b",
    affiliateUrl: "https://www.amazon.com/dp/example-blocks",
    platform: "Amazon",
    occasions: ["Birthday", "Christmas"],
    interests: ["Games", "STEM", "Creativity"],
    ageMin: 4,
    ageMax: 12,
  },
  {
    name: "Leather Wallet",
    description: "Slim, RFID-blocking full-grain leather wallet with six card slots.",
    price: 55.0,
    imageUrl: "https://images.unsplash.com/photo-1627123424574-724758594e93",
    affiliateUrl: "https://www.amazon.com/dp/example-wallet",
    platform: "Amazon",
    occasions: ["Father's Day", "Birthday", "Graduation"],
    interests: ["Fashion"],
    ageMin: 16,
    ageMax: 99,
  },
  {
    name: "Yoga Mat and Block Set",
    description: "Non-slip eco-friendly yoga mat bundled with two cork blocks and a carry strap.",
    price: 48.5,
    imageUrl: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f",
    affiliateUrl: "https://www.amazon.com/dp/example-yogaset",
    platform: "Amazon",
    occasions: ["Birthday", "New Year", "Mother's Day"],
    interests: ["Fitness", "Health", "Self-care"],
    ageMin: 12,
    ageMax: 99,
  },
  {
    name: "Gourmet Chocolate Tasting Box",
    description: "A curated selection of single-origin artisan chocolates from around the world.",
    price: 39.99,
    imageUrl: "https://images.unsplash.com/photo-1549007994-cb92caebd54b",
    affiliateUrl: "https://www.etsy.com/listing/example-chocolate",
    platform: "Etsy",
    occasions: ["Valentine's Day", "Anniversary", "Thank You"],
    interests: ["Food", "Cooking"],
    ageMin: 10,
    ageMax: 99,
  },
  {
    name: "Drone with 4K Camera",
    description: "Foldable camera drone with GPS return-to-home and 30 minutes of flight time.",
    price: 429.0,
    imageUrl: "https://images.unsplash.com/photo-1473968512647-3e447244af8f",
    affiliateUrl: "https://www.amazon.com/dp/example-drone",
    platform: "Amazon",
    occasions: ["Birthday", "Graduation", "Christmas"],
    interests: ["Photography", "Tech", "Outdoors"],
    ageMin: 16,
    ageMax: 99,
  },
];

async function main() {
  console.log(`Seeding ${gifts.length} gifts...`);

  await prisma.gift.deleteMany();
  await prisma.gift.createMany({ data: gifts });

  console.log("Seed complete.");
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
