// Display-only emoji for quiz options. Keyed by the canonical strings in
// gift-options.ts — purely cosmetic, never touches the values used for
// matching/filtering against the database.

export const RELATIONSHIP_EMOJI: Record<string, string> = {
  Partner: "💕",
  Friend: "🤙",
  Parent: "👪",
  Sibling: "🧑‍🤝‍🧑",
  Child: "🧒",
  Coworker: "💼",
  Other: "✨",
};

export const OCCASION_EMOJI: Record<string, string> = {
  Birthday: "🎂",
  Christmas: "🎄",
  Graduation: "🎓",
  Housewarming: "🏡",
  Wedding: "💍",
  Anniversary: "💐",
  "New Year": "🎉",
  "Family Gathering": "🍽️",
  "Get Well Soon": "🩹",
  "Mother's Day": "🌷",
  "Father's Day": "🧢",
  "Valentine's Day": "❤️",
  "Thank You": "🙏",
  Diwali: "🪔",
  Holi: "🎨",
  "Raksha Bandhan": "🧵",
  "Eid al-Fitr": "🌙",
  "Eid al-Adha": "🐑",
  Hanukkah: "🕎",
  Passover: "🍷",
  "Lunar New Year": "🧧",
  "Mid-Autumn Festival": "🥮",
  Nowruz: "🌱",
  Vaisakhi: "🌾",
  Onam: "🛶",
  Quinceañera: "👑",
  "Day of the Dead": "💀",
  Kwanzaa: "🕯️",
  "St. Patrick's Day": "☘️",
  Oktoberfest: "🍺",
  Carnival: "🎭",
  Vesak: "☸️",
  "Bar/Bat Mitzvah": "✡️",
  "Baby Shower": "🍼",
  Retirement: "🌴",
};

export const INTEREST_EMOJI: Record<string, string> = {
  Music: "🎵",
  Tech: "📱",
  Travel: "✈️",
  Photography: "📸",
  Art: "🎨",
  Coffee: "☕",
  Cooking: "🍳",
  Gaming: "🎮",
  Writing: "✍️",
  Fitness: "🏋️",
  Health: "🧘",
  Games: "🎲",
  Family: "👨‍👩‍👧",
  Gardening: "🌱",
  "Home Decor": "🛋️",
  Outdoors: "🏕️",
  Beauty: "💄",
  "Self-care": "🧖",
  Painting: "🖌️",
  Astronomy: "🔭",
  Romance: "💘",
  Sports: "⚽",
  STEM: "🔬",
  Creativity: "💡",
  Fashion: "👗",
  Food: "🍕",
  Jewelry: "💎",
  Personalized: "🏷️",
  Reading: "📚",
  Cars: "🏎️",
};
