/**
 * Reader for Shopify's public storefront product feed.
 *
 * Every Shopify store exposes `/products.json` without authentication — it's
 * generated by the platform and returns the same catalog data the storefront
 * renders. No key, no approval, no affiliate membership.
 *
 * We read only public catalogue fields (title, price, image, product URL) and
 * link every result back to the merchant's own product page. We identify
 * ourselves in the User-Agent and rate-limit between requests rather than
 * hammering anyone's storefront.
 */

const USER_AGENT = "GiftFinderBot/1.0 (+https://thegiftfinder.net; gift discovery, links back to merchant)";

export interface ShopifyVariant {
  id: number;
  title: string;
  /** Shopify sends money as a decimal *string*, e.g. "20.00". */
  price: string;
  compare_at_price?: string | null;
  available: boolean;
}

export interface ShopifyImage {
  src: string;
  width?: number;
  height?: number;
}

export interface ShopifyProduct {
  id: number;
  title: string;
  handle: string;
  body_html?: string | null;
  vendor?: string | null;
  product_type?: string | null;
  tags?: string[];
  variants?: ShopifyVariant[];
  images?: ShopifyImage[];
}

export class ShopifyFeedError extends Error {
  constructor(
    message: string,
    readonly status: number,
  ) {
    super(message);
    this.name = "ShopifyFeedError";
  }
}

/** One page of a store's public catalogue. Shopify caps `limit` at 250. */
export async function fetchProductsPage(
  domain: string,
  page: number,
  limit = 250,
): Promise<ShopifyProduct[]> {
  const url = new URL(`https://${domain}/products.json`);
  url.searchParams.set("limit", String(Math.min(limit, 250)));
  url.searchParams.set("page", String(page));

  const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
  if (!res.ok) {
    throw new ShopifyFeedError(`${domain} returned ${res.status}`, res.status);
  }

  const text = await res.text();
  let json: { products?: ShopifyProduct[] };
  try {
    json = JSON.parse(text) as { products?: ShopifyProduct[] };
  } catch {
    // Some stores put a storefront password page or HTML error behind this path.
    throw new ShopifyFeedError(`${domain} did not return JSON`, res.status);
  }

  return json.products ?? [];
}

/** First in-stock variant, falling back to the first variant of any kind. */
export function pickVariant(product: ShopifyProduct): ShopifyVariant | null {
  const variants = product.variants ?? [];
  return variants.find((v) => v.available) ?? variants[0] ?? null;
}

/**
 * First product image, resized by Shopify's CDN.
 *
 * The raw `src` is the original upload — routinely 1–2 MB PNGs, which makes
 * every card slow to paint and wastes optimizer time. Shopify's CDN resizes on
 * demand via `?width=`, so we ask for something sensible for a card at import
 * time rather than shipping the full-resolution original.
 */
export function pickImageUrl(product: ShopifyProduct, width = 900): string | null {
  const src = product.images?.[0]?.src;
  if (!src) return null;

  try {
    const url = new URL(src);
    url.searchParams.set("width", String(width));
    return url.toString();
  } catch {
    return src;
  }
}

/** `body_html` is real HTML; strip tags and entities down to a plain summary. */
export function htmlToText(html: string): string {
  const named: Record<string, string> = {
    amp: "&",
    lt: "<",
    gt: ">",
    quot: '"',
    apos: "'",
    nbsp: " ",
    mdash: "—",
    ndash: "–",
    hellip: "…",
    rsquo: "’",
    lsquo: "‘",
    ldquo: "“",
    rdquo: "”",
  };

  return html
    .replace(/<[^>]*>/g, " ")
    .replace(/&#(\d+);/g, (_, code: string) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-f]+);/gi, (_, hex: string) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&([a-z]+);/gi, (match, name: string) => named[name.toLowerCase()] ?? match)
    .replace(/\s+/g, " ")
    .trim();
}

export function productUrl(domain: string, handle: string): string {
  return `https://${domain}/products/${handle}`;
}
